import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  gitdbSidebar: [
    {
      type: 'category',
      label: 'GitDB',
      items: [{type: 'autogenerated', dirName: 'gitdb'}],
    },
  ],
  protocolSidebar: [
    {
      type: 'category',
      label: 'Protocol',
      items: [{type: 'autogenerated', dirName: 'protocol'}],
    },
  ],
  iosSidebar: [
    {
      type: 'category',
      label: 'Replycant iOS',
      items: [{type: 'autogenerated', dirName: 'replycant-ios'}],
    },
  ],
  webappSidebar: [
    {
      type: 'category',
      label: 'Webapp',
      items: [{type: 'autogenerated', dirName: 'replycant-webapp'}],
    },
  ],
  cliSidebar: [
    {
      type: 'category',
      label: 'CLI',
      link: {type: 'doc', id: 'cli/index'},
      items: [{type: 'autogenerated', dirName: 'cli'}],
    },
  ],
};

export default sidebars;
