import {
  KeyUsageFlags,
  KeyUsagesExtension,
  SubjectKeyIdentifierExtension,
  X509CertificateGenerator,
  PemConverter,
} from "@peculiar/x509";
import { x25519 } from "@noble/curves/ed25519.js";
import { bech32 } from "@scure/base";

export const IDENTITY_STORAGE_KEY = "replycant.identity.v1";
export const IDENTITY_PBKDF2_ITERATIONS = 150_000;
const SALT_BYTES = 16;
const IV_BYTES = 12;
const DEVICE_KEY_BYTES = 32;
const CERT_VALIDITY_YEARS = 100;
const CLIENT_KEY_HEADER = "x-replycant-client-key";
const CLIENT_CERT_HEADER = "x-replycant-client-cert";
const FALLBACK_DEVICE_NAME = "replycant-webapp";

export type IdentityWrap = "password" | "device";

// Persists only ciphertext so a localStorage dump never yields private keys.
export interface IdentityStorageRecord {
  version: 2;
  publicKeySsh: string;
  agePublicKey: string;
  deviceName: string;
  deviceUUID: string;
  createdAt: string;
  wrap: IdentityWrap;
  encryptedPayloadBase64: string;
  ivBase64: string;
  saltBase64?: string;
}

export interface DecryptedIdentity {
  privateKeyPem: string;
  certificatePem: string;
  publicKeySsh: string;
  agePublicKey: string;
  agePrivateKeyBase64: string;
  deviceName: string;
  deviceUUID: string;
  createdAt: string;
}

interface IdentitySecretPayload {
  privateKeyPem: string;
  certificatePem: string;
  agePrivateKeyBase64: string;
}

// Selects how the AES wrapping key is obtained for encrypt and unlock.
export type IdentityKeySource =
  | { wrap: "password"; password: string }
  | { wrap: "device"; deviceKey: Uint8Array | null };

export interface CreateIdentityOptions {
  keySource: IdentityKeySource;
  deviceName: string;
  deviceUUID?: string;
}

// Keeps binary-to-text conversions deterministic for encrypted payload persistence.
const bytesToBase64 = (bytes: Uint8Array): string => btoa(String.fromCharCode(...bytes));

// Normalizes binary digests to lowercase hex so QR payload verification matches iOS formatting.
const bytesToHex = (bytes: Uint8Array): string =>
  Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");

// Restores encrypted payload bytes from local storage records.
const base64ToBytes = (encoded: string): Uint8Array =>
  Uint8Array.from(atob(encoded), (char) => char.charCodeAt(0));

// Narrows Uint8Array to DOM BufferSource for strict TS lib compatibility.
const asBufferSource = (bytes: Uint8Array): BufferSource => bytes as unknown as BufferSource;

// Wraps DER data into PEM blocks so TLS agents can consume browser-generated material.
const derToPem = (label: string, der: ArrayBuffer): string => {
  const body = bytesToBase64(new Uint8Array(der)).match(/.{1,64}/g)?.join("\n") ?? "";
  return `-----BEGIN ${label}-----\n${body}\n-----END ${label}-----\n`;
};

// Parses PEM certificates into canonical DER bytes so hash comparisons ignore formatting differences.
const parsePemCertificateDer = (certificatePem: string): Uint8Array => {
  const normalized = certificatePem
    .replace("-----BEGIN CERTIFICATE-----", "")
    .replace("-----END CERTIFICATE-----", "")
    .replace(/\s+/g, "");
  if (!normalized) {
    throw new Error("Certificate PEM is empty.");
  }
  try {
    return base64ToBytes(normalized);
  } catch {
    throw new Error("Certificate PEM is invalid.");
  }
};

// Encodes raw X25519 public key bytes into Bech32 `age1...` format for cross-device key exchange.
const encodeAgePublicKey = (publicKey: Uint8Array): string =>
  bech32.encode("age", bech32.toWords(publicKey));

// Encodes SSH binary strings to build OpenSSH-compatible `ecdsa-sha2-nistp256` public keys.
const encodeSshString = (value: Uint8Array): Uint8Array => {
  const out = new Uint8Array(4 + value.length);
  const view = new DataView(out.buffer);
  view.setUint32(0, value.length);
  out.set(value, 4);
  return out;
};

// Produces the OpenSSH key payload so iOS onboarding can reuse established public key workflows.
const toSshPublicKey = (rawPublicKey: Uint8Array): string => {
  const keyType = new TextEncoder().encode("ecdsa-sha2-nistp256");
  const curve = new TextEncoder().encode("nistp256");
  const payload = new Uint8Array(
    encodeSshString(keyType).length + encodeSshString(curve).length + encodeSshString(rawPublicKey).length,
  );
  let offset = 0;
  for (const part of [encodeSshString(keyType), encodeSshString(curve), encodeSshString(rawPublicKey)]) {
    payload.set(part, offset);
    offset += part.length;
  }
  return `ecdsa-sha2-nistp256 ${bytesToBase64(payload)}`;
};

// Normalizes device names so pubkey filenames generated by iOS stay predictable and filesystem-safe.
export const sanitizeDeviceName = (input: string): string => {
  const normalized = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_\s]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "");
  return normalized || FALLBACK_DEVICE_NAME;
};

// Generates UUID metadata for device-linking payloads consumed by iOS scanner validation.
export const createDeviceUuid = (): string => {
  if (typeof crypto.randomUUID === "function") {
    return crypto.randomUUID().toLowerCase();
  }
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
};

// Provides a sensible default device name so first-run setup can prefill identity metadata fields.
export const getDefaultDeviceName = (): string => {
  const ua = navigator.userAgent.toLowerCase();
  if (ua.includes("iphone")) return "iphone-webapp";
  if (ua.includes("ipad")) return "ipad-webapp";
  if (ua.includes("android")) return "android-webapp";
  if (ua.includes("mac")) return "mac-webapp";
  if (ua.includes("windows")) return "windows-webapp";
  if (ua.includes("linux")) return "linux-webapp";
  return FALLBACK_DEVICE_NAME;
};

// Derives an AES key from the user's password so persisted identity secrets stay unreadable at rest.
const derivePasswordKey = async (password: string, salt: Uint8Array): Promise<CryptoKey> => {
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveKey"],
  );
  return crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt: asBufferSource(salt),
      iterations: IDENTITY_PBKDF2_ITERATIONS,
      hash: "SHA-256",
    },
    keyMaterial,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
};

// Imports the OS-backed device key as AES-GCM material for silent Electron unlock.
const importDeviceAesKey = async (deviceKey: Uint8Array): Promise<CryptoKey> => {
  if (deviceKey.length !== DEVICE_KEY_BYTES) {
    throw new Error(`Device key must be ${DEVICE_KEY_BYTES} bytes.`);
  }
  return crypto.subtle.importKey(
    "raw",
    asBufferSource(deviceKey),
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
};

// Resolves the AES wrapping key from either a password or the Electron device key.
const resolveWrappingKey = async (
  keySource: IdentityKeySource,
  salt?: Uint8Array,
): Promise<{ key: CryptoKey; salt?: Uint8Array }> => {
  if (keySource.wrap === "password") {
    const password = keySource.password.trim();
    if (!password) {
      throw new Error("Password is required to protect identity secrets.");
    }
    const resolvedSalt = salt ?? crypto.getRandomValues(new Uint8Array(SALT_BYTES));
    return { key: await derivePasswordKey(password, resolvedSalt), salt: resolvedSalt };
  }
  if (!keySource.deviceKey) {
    throw new Error(
      "Device key is unavailable. Restart onboarding or restore OS keyring access.",
    );
  }
  return { key: await importDeviceAesKey(keySource.deviceKey) };
};

// Encrypts identity secrets so localStorage never holds private key material in cleartext.
const encryptIdentityPayload = async (
  payload: IdentitySecretPayload,
  keySource: IdentityKeySource,
): Promise<{ encryptedPayloadBase64: string; ivBase64: string; saltBase64?: string }> => {
  const { key, salt } = await resolveWrappingKey(keySource);
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    key,
    new TextEncoder().encode(JSON.stringify(payload)),
  );
  return {
    encryptedPayloadBase64: bytesToBase64(new Uint8Array(ciphertext)),
    ivBase64: bytesToBase64(iv),
    ...(salt ? { saltBase64: bytesToBase64(salt) } : {}),
  };
};

// Decrypts persisted identity secrets so request-scoped auth headers can be built in RAM.
const decryptIdentityPayload = async (
  record: IdentityStorageRecord,
  keySource: IdentityKeySource,
): Promise<IdentitySecretPayload> => {
  if (!record.encryptedPayloadBase64 || !record.ivBase64) {
    throw new Error("Stored identity payload is incomplete.");
  }
  if (record.wrap === "password" && !record.saltBase64) {
    throw new Error("Stored identity payload is incomplete.");
  }
  if (keySource.wrap !== record.wrap) {
    throw new Error(`Identity wrap mode mismatch: expected ${record.wrap}.`);
  }
  const salt = record.saltBase64 ? base64ToBytes(record.saltBase64) : undefined;
  const { key } = await resolveWrappingKey(keySource, salt);
  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: asBufferSource(base64ToBytes(record.ivBase64)) },
    key,
    asBufferSource(base64ToBytes(record.encryptedPayloadBase64)),
  );
  return JSON.parse(new TextDecoder().decode(plaintext)) as IdentitySecretPayload;
};

// Prevents opaque runtime crashes by requiring a secure origin before WebCrypto key operations begin.
const assertWebCryptoSupport = (): void => {
  if (typeof crypto?.subtle?.generateKey === "function") return;
  const origin = typeof window !== "undefined" ? window.location.origin : "this environment";
  throw new Error(
    `WebCrypto is unavailable on ${origin}. Open the webapp on https://<host> or localhost to generate an identity.`,
  );
};

// Creates long-lived browser-owned credentials that are always encrypted before persistence.
export const createIdentity = async (options: CreateIdentityOptions): Promise<IdentityStorageRecord> => {
  assertWebCryptoSupport();
  const agePrivateKey = x25519.utils.randomSecretKey();
  const agePublicKey = encodeAgePublicKey(x25519.getPublicKey(agePrivateKey));
  const keys = await crypto.subtle.generateKey(
    { name: "ECDSA", namedCurve: "P-256" },
    true,
    ["sign", "verify"],
  );
  const privatePkcs8 = await crypto.subtle.exportKey("pkcs8", keys.privateKey);
  const publicRaw = new Uint8Array(await crypto.subtle.exportKey("raw", keys.publicKey));
  const privateKeyPem = derToPem("PRIVATE KEY", privatePkcs8);
  const now = new Date();
  const notAfter = new Date(now);
  notAfter.setFullYear(notAfter.getFullYear() + CERT_VALIDITY_YEARS);
  const cert = await X509CertificateGenerator.createSelfSigned({
    serialNumber: `${Date.now()}`,
    name: "CN=replycant-webapp",
    notBefore: now,
    notAfter,
    signingAlgorithm: { name: "ECDSA", hash: "SHA-256" },
    keys,
    extensions: [
      new KeyUsagesExtension(KeyUsageFlags.digitalSignature | KeyUsageFlags.keyEncipherment, true),
      await SubjectKeyIdentifierExtension.create(keys.publicKey),
    ],
  });
  const certificatePem = PemConverter.encode(cert.rawData, "CERTIFICATE");
  const deviceName = sanitizeDeviceName(options.deviceName);
  const deviceUUID = (options.deviceUUID ?? createDeviceUuid()).toLowerCase();
  const encrypted = await encryptIdentityPayload(
    {
      privateKeyPem,
      certificatePem,
      agePrivateKeyBase64: bytesToBase64(agePrivateKey),
    },
    options.keySource,
  );
  return {
    version: 2,
    publicKeySsh: toSshPublicKey(publicRaw),
    agePublicKey,
    deviceName,
    deviceUUID,
    createdAt: now.toISOString(),
    wrap: options.keySource.wrap,
    ...encrypted,
  };
};

// Persists encrypted identity records so users can resume sessions after reloads.
export const saveIdentityRecord = (record: IdentityStorageRecord): void => {
  localStorage.setItem(IDENTITY_STORAGE_KEY, JSON.stringify(record));
};

// Validates a persisted identity envelope without rewriting storage or accepting plaintext leftovers.
export const loadIdentityRecord = (): IdentityStorageRecord | null => {
  const raw = localStorage.getItem(IDENTITY_STORAGE_KEY);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    if (parsed.version !== 2) return null;
    if (parsed.wrap !== "password" && parsed.wrap !== "device") return null;
    if (typeof parsed.publicKeySsh !== "string" || !parsed.publicKeySsh) return null;
    if (typeof parsed.agePublicKey !== "string" || !parsed.agePublicKey) return null;
    if (typeof parsed.deviceName !== "string" || !parsed.deviceName) return null;
    if (typeof parsed.deviceUUID !== "string" || !parsed.deviceUUID) return null;
    if (typeof parsed.createdAt !== "string" || !parsed.createdAt) return null;
    if (typeof parsed.encryptedPayloadBase64 !== "string" || !parsed.encryptedPayloadBase64) {
      return null;
    }
    if (typeof parsed.ivBase64 !== "string" || !parsed.ivBase64) return null;
    if (parsed.wrap === "password" && typeof parsed.saltBase64 !== "string") return null;
    // Reject records that still carry cleartext secret fields from older formats.
    if (
      "privateKeyPem" in parsed ||
      "certificatePem" in parsed ||
      "agePrivateKeyBase64" in parsed ||
      "encrypted" in parsed
    ) {
      return null;
    }
    return {
      version: 2,
      publicKeySsh: parsed.publicKeySsh,
      agePublicKey: parsed.agePublicKey,
      deviceName: sanitizeDeviceName(parsed.deviceName),
      deviceUUID: parsed.deviceUUID.toLowerCase(),
      createdAt: parsed.createdAt,
      wrap: parsed.wrap,
      encryptedPayloadBase64: parsed.encryptedPayloadBase64,
      ivBase64: parsed.ivBase64,
      ...(typeof parsed.saltBase64 === "string" ? { saltBase64: parsed.saltBase64 } : {}),
    };
  } catch {
    return null;
  }
};

// Removes persisted identity so users can explicitly restart onboarding from a clean slate.
export const clearIdentityRecord = (): void => {
  localStorage.removeItem(IDENTITY_STORAGE_KEY);
};

// Unlocks persisted identity into memory for request-time mTLS header generation.
export const unlockIdentity = async (
  record: IdentityStorageRecord,
  keySource: IdentityKeySource,
): Promise<DecryptedIdentity> => {
  const decrypted = await decryptIdentityPayload(record, keySource);
  return {
    ...decrypted,
    publicKeySsh: record.publicKeySsh,
    agePublicKey: record.agePublicKey,
    deviceName: record.deviceName,
    deviceUUID: record.deviceUUID,
    createdAt: record.createdAt,
  };
};

// Builds the proxy auth headers so browser identity material reaches gitd/lfs mTLS handshakes.
export const buildMtlsHeaders = (
  identity: Pick<DecryptedIdentity, "privateKeyPem" | "certificatePem">,
): Record<string, string> => ({
  [CLIENT_KEY_HEADER]: bytesToBase64(new TextEncoder().encode(identity.privateKeyPem)),
  [CLIENT_CERT_HEADER]: bytesToBase64(new TextEncoder().encode(identity.certificatePem)),
});

// Serializes iOS-compatible linking payload so scanner validation can parse public key identity metadata.
export const buildPublicKeyQrPayload = (
  identity: Pick<DecryptedIdentity, "publicKeySsh" | "deviceName" | "deviceUUID" | "agePublicKey">,
  caHash: string,
): string =>
  JSON.stringify({
    pubkey: identity.publicKeySsh,
    age_pubkey: identity.agePublicKey,
    name: identity.deviceName,
    uuid: identity.deviceUUID,
    ca_hash: caHash,
  });

// Hashes canonical certificate bytes so iOS and webapp can compare CA identity deterministically.
export const computeCaHash = async (certificatePem: string): Promise<string> => {
  const derBytes = parsePemCertificateDer(certificatePem);
  const digest = await crypto.subtle.digest("SHA-256", asBufferSource(derBytes));
  return bytesToHex(new Uint8Array(digest));
};
